# -*- coding: utf-8 -*-
"""2420080041_WEEK3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g00GoKQ2AVPnO92hu7nlf7UgyQ-haeCh
"""

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report

# 2) Load the Iris dataset
data = load_iris()
X = data.data          # Feature matrix
y = data.target        # Target labels
target_names = data.target_names
print("Original Data Shape:",X.shape)
scaler = StandardScaler()
X_standardized = scaler.fit_transform(X)
minmax = MinMaxScaler()
X_normalized = minmax.fit_transform(X)
print("scaler",X_standardized)
print("Minmax",X_normalized)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_standardized)
print("\nExplained Variance Ratio:")
for i, var in enumerate(pca.explained_variance_ratio_):
  print(f"Principal Component {i+1}: {var:.4f}")
print("Cumulative Explained Variance:",np.cumsum(pca.explained_variance_ratio_))

plt.figure()
for i, target in enumerate(target_names):
  plt.scatter(X_pca[y ==i, 0], X_pca[y ==i, 1], label=target)
plt.xlabel("PrincipalComponent 1")
plt.ylabel("PrincipalComponent 2")
plt.title("PCA(2D Projection)")
plt.legend()
plt.show()

pca_full =PCA()
pca_full.fit(X_standardized)
plt.figure()
plt.plot(np.cumsum(pca_full.explained_variance_ratio_),marker='o')
plt.xlabel("Number of Components")
plt.ylabel("Cumulative ExplainedVariance")
plt.title("Scree Plot")
plt.grid()
plt.show()